// <auto-generated />
// 由 tools/contract-gen 从 HoYoEnhance.Contracts 的 C# DTO 生成，请勿手改。

export type GameId = 'genshin' | 'starRail';

export type LogLevel = 'Trace' | 'Debug' | 'Info' | 'Warn' | 'Error';

export interface GameProfile {
  targetFps: number;
  enabled: boolean;
  antiBlurPerspective: boolean;
  antiBlurDiveMosaic: boolean;
  hideUid: boolean;
  gamePath: string | null;
}

export interface GameProfiles {
  genshin: GameProfile;
  starRail: GameProfile;
}

export interface UnlockerConfig {
  activeGame: GameId;
  games: GameProfiles;
  masterEnabled: boolean;
  autoWatch: boolean;
  startMinimized: boolean;
  autoStartWithWindows: boolean;
  autoStartAsAdministrator: boolean;
  pollIntervalMs: number;
  safetyNoticeAcknowledged: boolean;
  showSafetyNoticeOnStartup: boolean;
  defenderExclusionApplied: boolean;
  debugLogging: boolean;
  logLevel: LogLevel;
  logRetainDays: number;
  suppressAdminHint: boolean;
}
