// <auto-generated />
// 由 tools/contract-gen 从 HoYoEnhance.Contracts 的 C# DTO 生成，请勿手改。

export type GameId = 'genshin' | 'starRail';

export type LogLevel = 'Trace' | 'Debug' | 'Info' | 'Warn' | 'Error';

export interface GameProfile {
  targetFps: number;
  enabled: boolean;
  antiBlurPerspective: boolean;
  antiBlurDiveMosaic: boolean;
  hideUid: boolean;
  gamePath: string | null;
}

export interface GameProfiles {
  genshin: GameProfile;
  starRail: GameProfile;
}

export interface UnlockerConfig {
  activeGame: GameId;
  games: GameProfiles;
  masterEnabled: boolean;
  autoWatch: boolean;
  startMinimized: boolean;
  autoStartWithWindows: boolean;
  autoStartAsAdministrator: boolean;
  pollIntervalMs: number;
  safetyNoticeAcknowledged: boolean;
  showSafetyNoticeOnStartup: boolean;
  defenderExclusionApplied: boolean;
  debugLogging: boolean;
  logLevel: LogLevel;
  logRetainDays: number;
  suppressAdminHint: boolean;
}

export interface GameDefinition {
  id: GameId;
  key: string;
  displayName: string;
  shortName: string;
  processNames: readonly string[];
  executableNames: readonly string[];
  stubFileName: string;
  fpsViaRegistry: boolean;
  lockedFps: number;
  supportsDiveMosaic: boolean;
}

export const GAME_CATALOG = {
  genshin: {
    id: 'genshin',
    key: 'genshin',
    displayName: '原神',
    shortName: '原神',
    processNames: ['YuanShen', 'GenshinImpact'],
    executableNames: ['YuanShen', 'GenshinImpact'],
    stubFileName: 'FpsUnlockerStub.dll',
    fpsViaRegistry: false,
    lockedFps: 0,
    supportsDiveMosaic: true,
  },
  starRail: {
    id: 'starRail',
    key: 'starRail',
    displayName: '崩坏：星穹铁道',
    shortName: '星穹铁道',
    processNames: ['StarRail'],
    executableNames: ['StarRail'],
    stubFileName: 'StarRailStub.dll',
    fpsViaRegistry: true,
    lockedFps: 120,
    supportsDiveMosaic: false,
  },
} as const satisfies Record<GameId, GameDefinition>;

export const DEFAULT_GAME_ID: GameId = 'genshin';
export const GAME_IDS = Object.keys(GAME_CATALOG) as GameId[];
