using System.Reflection;
using System.Text;
using System.Text.Json;
using HoYoEnhance.Contracts;

const string DefaultOutput = "src/Ui/src/lib/bridge.generated.ts";

var checkOnly = args.Contains("--check", StringComparer.Ordinal);
var output = GetArg(args, "--out") ?? DefaultOutput;
var fullOutput = Path.GetFullPath(output);
var generated = ContractGenerator.Generate();

if (checkOnly)
{
    if (!File.Exists(fullOutput))
    {
        Console.Error.WriteLine($"契约文件不存在: {fullOutput}");
        return 1;
    }

    var current = File.ReadAllText(fullOutput);
    if (!string.Equals(Normalize(current), Normalize(generated), StringComparison.Ordinal))
    {
        Console.Error.WriteLine(
            $"C# DTO 与 TypeScript 契约不一致: {fullOutput}\n" +
            "运行 dotnet run --project tools/contract-gen/HoYoEnhance.ContractGen.csproj -- --out src/Ui/src/lib/bridge.generated.ts");
        return 1;
    }

    Console.WriteLine("C# DTO 与 TypeScript 契约一致");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(fullOutput)!);
File.WriteAllText(fullOutput, generated, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"已生成 {fullOutput}");
return 0;

static string? GetArg(string[] values, string name)
{
    var index = Array.IndexOf(values, name);
    return index >= 0 && index + 1 < values.Length ? values[index + 1] : null;
}

static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";

internal static class ContractGenerator
{
    private static readonly Type[] Enums =
    [
        typeof(GameId),
        typeof(LogLevel),
    ];

    private static readonly Type[] Dtos =
    [
        typeof(GameProfileDto),
        typeof(GameProfilesDto),
        typeof(UnlockerConfigDto),
    ];

    public static string Generate()
    {
        var output = new StringBuilder();
        output.AppendLine("// <auto-generated />");
        output.AppendLine("// 由 tools/contract-gen 从 HoYoEnhance.Contracts 的 C# DTO 生成，请勿手改。");
        output.AppendLine();

        foreach (var type in Enums)
        {
            output.AppendLine(GenerateEnum(type));
            output.AppendLine();
        }

        foreach (var type in Dtos)
        {
            output.AppendLine(GenerateInterface(type));
            output.AppendLine();
        }

        output.AppendLine(GenerateGameDefinitions());

        return output.ToString().Replace("\r\n", "\n").TrimEnd() + "\n";
    }

    private static string GenerateGameDefinitions()
    {
        var output = new StringBuilder();
        output.AppendLine("export interface GameDefinition {");
        output.AppendLine("  id: GameId;");
        output.AppendLine("  key: string;");
        output.AppendLine("  displayName: string;");
        output.AppendLine("  shortName: string;");
        output.AppendLine("  processNames: readonly string[];");
        output.AppendLine("  executableNames: readonly string[];");
        output.AppendLine("  stubFileName: string;");
        output.AppendLine("  fpsViaRegistry: boolean;");
        output.AppendLine("  lockedFps: number;");
        output.AppendLine("  supportsDiveMosaic: boolean;");
        output.AppendLine("}");
        output.AppendLine();
        output.AppendLine("export const GAME_CATALOG = {");
        foreach (var game in GameDefinitions.All)
        {
            var key = ToTsGameId(game.Id);
            if (!string.Equals(game.Key, key, StringComparison.Ordinal))
                throw new InvalidOperationException($"游戏目录 key 与 GameId 不一致: {game.Key} != {key}");
            output.AppendLine($"  {key}: {{");
            output.AppendLine($"    id: '{Escape(ToTsGameId(game.Id))}',");
            output.AppendLine($"    key: '{Escape(game.Key)}',");
            output.AppendLine($"    displayName: '{Escape(game.DisplayName)}',");
            output.AppendLine($"    shortName: '{Escape(game.ShortName)}',");
            output.AppendLine($"    processNames: [{string.Join(", ", game.ProcessNames.Select(value => $"'{Escape(value)}'"))}],");
            output.AppendLine($"    executableNames: [{string.Join(", ", game.ExecutableNames.Select(value => $"'{Escape(value)}'"))}],");
            output.AppendLine($"    stubFileName: '{Escape(game.StubFileName)}',");
            output.AppendLine($"    fpsViaRegistry: {game.FpsViaRegistry.ToString().ToLowerInvariant()},");
            output.AppendLine($"    lockedFps: {game.LockedFps},");
            output.AppendLine($"    supportsDiveMosaic: {game.SupportsDiveMosaic.ToString().ToLowerInvariant()},");
            output.AppendLine("  },");
        }
        output.AppendLine("} as const satisfies Record<GameId, GameDefinition>;");
        output.AppendLine();
        output.AppendLine($"export const DEFAULT_GAME_ID: GameId = '{Escape(ToTsGameId(GameDefinitions.DefaultGame))}';");
        output.AppendLine("export const GAME_IDS = Object.keys(GAME_CATALOG) as GameId[];");
        return output.ToString().TrimEnd();
    }

    private static string ToTsGameId(GameId game) =>
        game.GetType().GetField(game.ToString())?.GetCustomAttribute<TsValueAttribute>()?.Value ?? game.ToString();

    private static string GenerateEnum(Type type)
    {
        var values = type.GetFields(BindingFlags.Public | BindingFlags.Static)
            .Select(field => field.GetCustomAttribute<TsValueAttribute>()?.Value ?? field.Name)
            .Select(value => $"'{Escape(value)}'");
        return $"export type {TsName(type)} = {string.Join(" | ", values)};";
    }

    private static string GenerateInterface(Type type)
    {
        var nullability = new NullabilityInfoContext();
        var lines = new List<string> { $"export interface {TsName(type)} {{" };
        foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
                     .OrderBy(property => property.MetadataToken))
        {
            var propertyName = JsonNamingPolicy.CamelCase.ConvertName(property.Name);
            var info = nullability.Create(property);
            lines.Add($"  {propertyName}: {TsType(property, info)};");
        }
        lines.Add("}");
        return string.Join("\n", lines);
    }

    private static string TsType(PropertyInfo property, NullabilityInfo nullability)
    {
        var overrideType = property.GetCustomAttribute<TsTypeAttribute>()?.Type;
        if (overrideType is not null) return overrideType;
        return TsType(property.PropertyType, nullability.ReadState == NullabilityState.Nullable);
    }

    private static string TsType(Type type, bool nullable)
    {
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying is not null)
        {
            type = underlying;
            nullable = true;
        }

        var result = type switch
        {
            _ when type == typeof(string) => "string",
            _ when type == typeof(bool) => "boolean",
            _ when type == typeof(byte) || type == typeof(sbyte)
                   || type == typeof(short) || type == typeof(ushort)
                   || type == typeof(int) || type == typeof(uint)
                   || type == typeof(long) || type == typeof(ulong)
                   || type == typeof(float) || type == typeof(double)
                   || type == typeof(decimal) => "number",
            _ when type.IsEnum => TsName(type),
            _ when type.IsArray => $"readonly {TsType(type.GetElementType()!, false)}[]",
            _ when type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IReadOnlyList<>) =>
                $"readonly {TsType(type.GetGenericArguments()[0], false)}[]",
            _ when type.GetCustomAttribute<TsNameAttribute>() is not null => TsName(type),
            _ => throw new InvalidOperationException($"契约生成器不支持类型 {type.FullName}"),
        };

        return nullable ? $"{result} | null" : result;
    }

    private static string TsName(MemberInfo type) =>
        type.GetCustomAttribute<TsNameAttribute>()?.Name ?? type.Name;

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("'", "\\'");
}
