<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>HoYoEnhance.Contracts</AssemblyName>
    <RootNamespace>HoYoEnhance.Contracts</RootNamespace>
  </PropertyGroup>
</Project>
